name: kbot_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pyautogui
      - opencv-python
      - pytesseract
      - Pillow
      - keyboard
      - tk
      - customtkinter
